### ISSUE TITLE
Analysis of tools and architecture for KPI tracking service

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-misc-tools#16]
Get an overview of the tools needed to implement the key performance indicator tool and design application architecture and database

**Sub-tasks**

- [x] Select frontend for inspecting metrics
  - Initially, we'll select grafana as a front-end, as it can integrate directly into a postgres database.
- [x] Overview of rust SDK
- [x] Look into how Grafana integrates into database
- [x] Database structure
- [x] Feature proposal
