### ISSUE TITLE
[KPI-tracker] Store collected metrics in postgresql database

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-misc-tools#27]
To be able to extract the collected metrics, they should be stored in a database. A draft of the design can be seen [here](https://dbdiagram.io/d/63bbc13a6afaa541e5d129e7).

**This includes:**

- [x] Create database schema in SQL
- [x] Connect to (and use) database from service
  - [x] Restore process from most recent block height stored
  - [x] Insert data transactionally by block
