### ISSUE TITLE
Polish the genesis generation tool

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-misc-tools#3]
**Task description**

This is a continuation of #2 and its goal is to make the tool more polished, and make it handle errors better.

**Sub-tasks**
- [ ] Make the prototype handle all genesis versions. 
- [ ] Test genesis generation with all the different versions.
- [ ] Document the input format and behaviour of the tool
