### ISSUE TITLE
[KPI-tracker] Visualize collected metrics with Grafana

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-misc-tools#32]
Use grafana to visualize the data collected by the KPI-tracker service. Data is generally collected per block (and thus block time), enabling time series format for all metrics.

- [x] Set up Grafana locally
- [x] Transactions
  - [x] Number of transactions
  - [x] Number of rejected transactions
  - [x] Transaction fees paid
- [x] Accounts
  - [x] Number of accounts
  - [x] Number of active accounts (30 days)
    - Is very slow/heavy
  - [x] Number of initial accounts
- [x] Smart contracts
  - [x] Number of smart contract modules
  - [x] Number of smart contract intances
  - [x] Number of active smart contract instances (30 days)
    - Is very slow/heavy
- [x] Misc
  - [x] Total value staked (protocol version 4 and later only for now)
- [x] Optimize account/contract activeness queries (2d timebox)
- [x] Make "deployable" configuration
