### ISSUE TITLE
[KPI-tracker] Make service more robust for production

### ISSUE THREAD

**Issue by soerenbf** [Concordium/concordium-misc-tools#33]
The current implementation is fragile in a number of ways when comparing it to the implementation of f.x. the transaction logger. To make the service more robust we need to do the following:

- [x] Allow configuration with a list of node endpoints
  - [x] Finalization max time behind
- [x] Allow configuration through environment variables
- [x] Concurrent querying for catchup
- [x] Gracefully stop when receiving stop signal
- [x] Error handling
  - [x] Endpoint connection lost
  - [x] DB connection lost
