### ISSUE TITLE
Cleanup genesis generation scripts in concordium-base & concordium-node

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-misc-tools#4]
**Task description**

This follows #2 and #3 and its goal is to replace the more complex genesis generation scripts with example usage of the new tool.

The following must be updated/deleted

- [x] The docker build file for current set of genesis tools in concordium-base
- [x] The "genesis" tool in concordium-base should be removed
- [x] The python script to generate genesis in concordium-node (in scripts/genesis) should be removed and the instructions there should be replaced by instructing the user to use this tool, with an example configuration file.
- [ ] In the genesis_data repository, instructions on how to generate genesis should be replaced.
