### ISSUE TITLE
Test front end for `walletConnect` 

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-misc-tools#53]
**Task description**

Create a test bench front end for testing various positive/negative scenarios of how a front end could interact with the mobile wallets (using wallet connect). The front end should display all responses (e.g. error messages returned as well as transaction hashes returned) for further investigation.

The front end uses the `react-components`/`wallet-connectors` libraries to create the connection between mobile wallets and the front end: https://github.com/Concordium/concordium-dapp-libraries/tree/main/packages

**Sub-tasks**

The front end should have sections for testing the following scenarios:

- [x] Button for walletConnect connection.

- [x] Display connected account address.

Positive testing:

- [x] A test sending a simple CCD transfer to another account.

- [x] Sign an utf-8 string message and display the signature at the front end.

- [x] Sign a binary message and display the signature at the front end.

- [x] Setter/View functions:
An input field is provided for all these scenarios to input the correct type. Its value is serialized with the correct schema in the mobile wallets and sent to blockchain. An output field will display the deserialized value from the corresponding `view` function.

     - [x] set/view Address
     - [x] set/view AccountAddress
     - [x] set/view ContractAddress
     - [x] set/view string
     - [x] set/view Timestamp
     - [x] set/view Option
     - [x] set/view PublicKey
     - [x] set/view Signature
     - [x] set/view Hash
     - [x] set/view u8
     - [x] set/view u64
     - [x] set/view Object (containing fields for an Address, AccountAddress, ContractAddress, string, u8, u64)
     - [x] set/view Array (containing Addresses)

- [x] Above setter functions should be tested with `rawModuleSchemaBase64` and with individual `parameterSchemas`/`returnValueSchemas`

- [x] Above setter functions should have two versions (one that expects a positive CCD amount and one that expects an amount of  0 CCD sent to them). It should be possible to display the smart contract balance from the front end to check that the correct CCD amount was sent to the smart contract.

- [x] A test sending a transaction to a smart contract that calls another smart contract successfully.

Negative testing:

- [x] Above setter functions should be tested with a wrong schema (mismatched schema should cause the wallets not to be able to serialize the input parameter correctly). Error messages from the wallets should be displayed.

- [x] Above view functions should be tested with a wrong schema (mismatched schema should cause the wallets not to be able to deserialize the return value correctly). Error messages from the wallets should be displayed.

- [x] A test sending a transaction that reverts due to the smart contract logic.

- [x] A test sending a transaction to a smart contract that calls another smart contract but then reverts due to the smart contract logic.

- [x] It should be tested with a spoofed schema what happens if the smart contract does not have an entrypoint or does not have an entrypoint with the given input parameter. Meaning the mobile wallet should be able to create a valid transaction (given the spoofed schema/input parameter) but the blockchain does not have a valid smart contract/entrypoint for that transaction.

- [x] A test sending a transaction to an account that does not exist on chain.

- [x] Above setter/view functions should be tested by sending CCD to the function even if the function expects no CCD. Error messages should be displayed (potentially using a spoofed schema). 

Scenarios that are excluded for the first version of the test bench (but potential subjects for future versions):
- [ ] Toggle to select if the connection should be done to testnet or mainnet.
- [ ] Testing scheduled transfers.
- [ ] Testing shielded transfers.
- [ ] Testing deploying/initializing of new smart contract modules.

**Comment by abizjak** [comment]
Could we also add a test scenario where you sign a smart contract update that has inner calls to other contracts?

Otherwise looks like a good scope.
