### ISSUE TITLE
[Transaction generator] Support smart contract updates

### ISSUE THREAD

**Issue by lassemoldrup** [Concordium/concordium-misc-tools#84]
The transaction generator should support sending smart contract updates for the following contracts/methods:

- Mint CIS2 tokens ([contract](https://github.com/Concordium/concordium-rust-smart-contracts/tree/main/examples/cis2-nft))
- Wrap/Unwrap wrapped CCD ([contract](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-wccd))
- Transfer CIS2 tokens ([contract](https://github.com/Concordium/concordium-rust-smart-contracts/blob/main/examples/cis2-multi))
- Register Web3 ID credentials ([contract](https://github.com/Concordium/concordium-rust-smart-contracts/tree/main/examples/credential-registry))

**Sub-tasks**
- [x] Mint CIS2 tokens
- [x] Wrap/Unwrap wrapped CCD
- [x] Transfer CIS2 tokens
- [x] Register Web3 ID credentials
